import Link from 'next/link'
import Head from 'next/head'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { toast, ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import axios from 'axios'

export default function Register() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [password_confirmation, setPasswordConfirmation] = useState('')

  const router = useRouter()

  function register(event) {
    event.preventDefault()
    axios
      .post(
        'http://127.0.0.1:8000/api/register',
        {
          name: name,
          email: email,
          password: password,
          password_confirmation: password_confirmation,
        },
        {
          headers: {
            'content-type': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
          },
        },
        {
          withCredentials: true,
        }
      )
      .then(() => {
        router.push('/login')
      })
      .catch(error => {
        toast.error(`${error.message}`, {
          position: 'top-right',
          autoClose: 1000,
          pauseOnHover: false,
        })
      })
  }

  return (
    <div className="animate__animated animate__fadeIn bg-gray-200 min-h-screen flex flex-col">
      <Head>
        <title>register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      <div className="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <form
          onSubmit={register}
          className="bg-white px-6 py-8 rounded-xl shadow-md text-black w-full"
        >
          <h1 className="mb-8 text-3xl text-center font-bold">Sign up</h1>
          <input
            type="text"
            className="block border border-grey-light w-full p-3 rounded mb-4"
            name="fullname"
            placeholder="Full Name"
            required
            onChange={e => setName(e.target.value)}
          />
          <input
            type="text"
            className="block border border-grey-light w-full p-3 rounded mb-4"
            name="email"
            required
            placeholder="Email"
            onChange={e => setEmail(e.target.value)}
          />

          <input
            type="password"
            className="block border border-grey-light w-full p-3 rounded mb-4"
            name="password"
            required
            placeholder="Password"
            onChange={e => setPassword(e.target.value)}
          />
          <input
            type="password"
            className="block border border-grey-light w-full p-3 rounded mb-4"
            name="confirm_password"
            placeholder="Confirm Password"
            required
            onChange={e => setPasswordConfirmation(e.target.value)}
          />
          <button
            onClick={register}
            type="submit"
            className="w-full text-center font-semibold py-2 rounded bg-green-500 text-white focus:outline-none my-2"
          >
            Create Account
          </button>
        </form>

        <div className="text-grey-dark mt-6">
          Already have an account?
          <Link href="/login">
            <a
              className="p-2 font-bold font-sans border-b-2 border-double 
    border-transparent hover:border-current cursor-pointer select-none"
            >
              Log in
            </a>
          </Link>
        </div>
      </div>
    </div>
  )
}
